Repository docker/oscalkit, pull requests merged in 2019-01, with the labels that each got.

#31 Add oscalkit-test
  Gopkg.lock
  test/Readme.md
  test/TestCases.go
  test/main.go
  test/methods.go
  vendor/github.com/fatih/color/.travis.yml
  vendor/github.com/fatih/color/Gopkg.lock
  vendor/github.com/fatih/color/Gopkg.toml
  vendor/github.com/fatih/color/LICENSE.md
  vendor/github.com/fatih/color/README.md
  vendor/github.com/fatih/color/color.go
  vendor/github.com/fatih/color/color_test.go
  vendor/github.com/fatih/color/doc.go
  vendor/github.com/mattn/go-colorable/.travis.yml
  vendor/github.com/mattn/go-colorable/LICENSE
  vendor/github.com/mattn/go-colorable/README.md
  vendor/github.com/mattn/go-colorable/_example/escape-seq/main.go
  vendor/github.com/mattn/go-colorable/_example/logrus/main.go
  vendor/github.com/mattn/go-colorable/_example/title/main.go
  vendor/github.com/mattn/go-colorable/colorable_appengine.go
  vendor/github.com/mattn/go-colorable/colorable_others.go
  vendor/github.com/mattn/go-colorable/colorable_test.go
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/github.com/mattn/go-colorable/noncolorable.go
  vendor/github.com/mattn/go-isatty/.travis.yml
  vendor/github.com/mattn/go-isatty/LICENSE
  vendor/github.com/mattn/go-isatty/README.md
  vendor/github.com/mattn/go-isatty/doc.go
  vendor/github.com/mattn/go-isatty/example_test.go
  vendor/github.com/mattn/go-isatty/isatty_appengine.go
  vendor/github.com/mattn/go-isatty/isatty_bsd.go
  vendor/github.com/mattn/go-isatty/isatty_linux.go
  vendor/github.com/mattn/go-isatty/isatty_linux_ppc64x.go
  vendor/github.com/mattn/go-isatty/isatty_others.go
  vendor/github.com/mattn/go-isatty/isatty_others_test.go
  vendor/github.com/mattn/go-isatty/isatty_solaris.go
  vendor/github.com/mattn/go-isatty/isatty_windows.go
  vendor/github.com/mattn/go-isatty/isatty_windows_test.go
Labels: test

#32 Add implementation code generation
  Gopkg.lock
  cli/cmd/cmd.go
  cli/cmd/implementation.go
  generator/generator_test.go
  generator/mapper.go
  generator/reader.go
  impl/impl_test.go
  impl/implementation.go
  templates/implementation.go
  types/oscal/implementation/implementation.go
  types/oscal/profile/profile.go
  vendor/github.com/satori/go.uuid/.travis.yml
  vendor/github.com/satori/go.uuid/LICENSE
  vendor/github.com/satori/go.uuid/README.md
  vendor/github.com/satori/go.uuid/codec.go
  vendor/github.com/satori/go.uuid/codec_test.go
  vendor/github.com/satori/go.uuid/generator.go
  vendor/github.com/satori/go.uuid/generator_test.go
  vendor/github.com/satori/go.uuid/sql.go
  vendor/github.com/satori/go.uuid/sql_test.go
  vendor/github.com/satori/go.uuid/uuid.go
  vendor/github.com/satori/go.uuid/uuid_test.go
Labels: enhancement

#34 Add component guid mapping from excel
  impl/implementation.go
  templates/implementation.go
  types/oscal/implementation/implementation.go
Labels: enhancement

#52 Add modify-add feature
  generator/generator_test.go
  generator/manipulation.go
  generator/mapper.go
  generator/profile.go
  generator/reader.go
  templates/catalog.go
Labels: enhancement

#51 add regex to get componentID from control mapping
  impl/impl_test.go
  impl/implementation.go
  templates/implementation.go
Labels: enhancement

#68 Missing profile title workaround and move part traversal to separate file
  metaschema/types.tmpl
  types/oscal/catalog/catalog.go
  types/oscal/catalog/prose.go
  types/oscal/profile/profile.go
Labels: bug

#44 Tidying up some of the core OSCAL methods
  .dockerignore
  Dockerfile
  Dockerfile.build
  Makefile
  cli/cmd/cmd.go
  cli/cmd/convert/convert.go
  cli/cmd/convert/opencontrol.go
  cli/cmd/convert/oscal.go
  cli/cmd/validate.go
  cli/main.go
  types/oscal/catalog/href.go
  types/oscal/catalog/prose.go
  types/oscal/oscal.go
  validator/validator.go
  validator/validator_test.go
Labels: enhancement
